name: PR publish

on:
  issue_comment:
    types: [created]
jobs:
  pr-release-images:
    # Only on pull request and `publish`.
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'publish')
    env:
      PROD_IMAGE_NAME: ${GITHUB_REPOSITORY}
      VERSION: pr-${{ github.event.issue.number }}
    name: Release images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Required because issue_comment events are globals.
      # Check: https://github.com/actions/checkout/issues/331
      - name: Checkout Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: hub pr checkout ${{ github.event.issue.number }}
      - name: Docker login
        run: docker login ${DOCKER_HOST} -u ${DOCKER_USER} -p ${DOCKER_TOKEN}
        env:
          DOCKER_HOST: ""
          DOCKER_USER: slok
          DOCKER_TOKEN: ${{secrets.DOCKER_HUB_TOKEN}}
      - name: Build and publish images
        run: make build-publish-image-all
